### ISSUE TITLE
type error at createSession

### ISSUE THREAD

**Issue by nise** [tomassedovic/etherpad-lite-client-js#12]
Hello, 

thank you for your quick reply last time. I managed to run the module until I tried to create a session. Unfortunatly I cannot figure out any reason for that error in your code.

Thats the error:

/node_modules/etherpad-lite-client/main.js:63
            return callback({
                   ^
TypeError: string is not a function
    at IncomingMessage.<anonymous> (/home/abb/Documents/www2/e2script/node_modules/etherpad-lite-client/main.js:63:20)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)

**Comment by tomassedovic** [comment]
This project has not been maintained for a few years. I'm closing all pull requests and issues before archiving the repo on github. Sorry I hadn't done this sooner!
